# Generated by Django 4.2.4 on 2024-02-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0011_profile_confidentiality'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='6634816062:AAGjshTkVrQ7tMtMNfqCBg-SprNKjh6SGfA', max_length=255)),
                ('chat_id', models.CharField(default='@izzat_ansajfsnafis', max_length=100)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.profile', verbose_name='Author_post')),
            ],
        ),
    ]
