# Generated by Django 4.2.4 on 2024-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='error_message',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
