# Generated by Django 5.0 on 2023-12-26 12:30

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image')),
                ('content2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image')),
                ('content3', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image')),
                ('content4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image')),
                ('date_ad', models.DateTimeField(auto_now_add=True)),
                ('date_up', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Comment')),
                ('date_ad', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postmodel')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='StarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postmodel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
            },
        ),
    ]
