# Generated by Django 4.2.4 on 2023-12-30 12:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='conten11',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content10',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content5',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content6',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content7',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content8',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='content9',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='Image'),
        ),
    ]
