# Generated by Django 4.2.4 on 2024-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_conten11_postmodel_content11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image1',
            field=models.ImageField(blank=True, default='img/default/sport1.jpg', null=True, upload_to='images/post/', verbose_name='Image'),
        ),
    ]
