# Generated by Django 4.2.4 on 2024-01-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_starmodel_user_alter_starmodel_user_acc'),
        ('blog', '0006_alter_postmodel_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.profile', verbose_name='Author'),
        ),
    ]
