# Generated by Django 4.2.4 on 2024-01-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_starmodel_user_alter_starmodel_user_acc'),
        ('blog', '0007_alter_postmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='members.profile', verbose_name='Likes'),
        ),
    ]
