# Generated by Django 4.2.4 on 2024-01-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_profile_confidentiality'),
        ('blog', '0008_alter_postmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='starmodel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
        ),
    ]
