# Generated by Django 4.2.4 on 2024-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postmodel_view_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
    ]
