# Generated by Django 4.2.4 on 2024-01-24 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0005_alter_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
    ]
