# Generated by Django 4.2.4 on 2024-01-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_added', to='members.profile'),
        ),
        migrations.AlterField(
            model_name='starmodel',
            name='user_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_account', to='members.profile'),
        ),
    ]
