# Generated by Django 4.2.4 on 2024-01-24 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0008_alter_starmodel_user_alter_starmodel_user_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='starmodel',
            name='user_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
