# Generated by Django 4.2.4 on 2024-02-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_profile_confidentiality'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='Followers_profile', to='members.profile', verbose_name='Followers'),
        ),
    ]
