# Generated by Django 4.2.4 on 2024-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_profile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, to='members.profile', verbose_name='Followers'),
        ),
    ]
